# Generated by Django 4.2.6 on 2024-09-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bankloan',
            fields=[
                ('accno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('loanamt', models.IntegerField()),
                ('loanlimit', models.IntegerField()),
                ('phoneno', models.IntegerField()),
            ],
        ),
    ]
